#!/usr/bin/env sh
xset -dpms
xset s off
xset s noblank

chromium-browser \
  --window-position=0,0 \
  --start-fullscreen \
  --noerrdialogs \
  --disable-translate \
  --no-first-run \
  --fast \
  --fast-start \
  --disable-infobars \
  --disable-features=TranslateUI \
  --overscroll-history-navigation=0 \
  --disable-pinch
